### PR TITLE
LG tvs support

### PR DESCRIPTION
**Pull request by linuxenko**
npm push it please

### CODE REVIEW

**Comment by jaruba** [comment]
I would love for this to work..

giphy 7


What did you use for ssdp discovery in your tests? I heard good things about [nodecast-js](https://github.com/gyzerok/nodecast-js)

**Comment by linuxenko** [comment]
Yes, nodecast-js are good tool , i mean ssdp implementation , but .. it creates a list of found devices inside of himself and does not update any status of this devices , not so much useful part.

**Comment by thibauts** [comment]
Hi @linuxenko, thanks for your PR. How do your commits affect other TVs apart from LGs ? I'm all for having maximum compatibility but I'd prefer not to lose some while gaining others.

Regarding `protocolInfo`, where did you get this `'http-get:*:video/mp4:DLNA.ORG_PN=AVC_MP4_BL_CIF15_AAC_520;'` ? Having this hard-coded probably won't play well with video formats other than MP4. One way to handle this specific problem would be to call `getSupportedProtocols` internally, caching it, and looking it up on `load` to find the best match for the requested mime type.

Regarding subtitles, you uncommented a block of code that *will* break compatibility for many people. We need to find a better way to handle this case. I'm sure we can find one.

First, does the `text/srt` mime type appear in `getSupportedProtocols` for your TV ? If it does, we could condition the uncommented block on this fact. It would make us sure the receiving device can handle it.

In fact, we could handle it like what I proposed for the video mime type, ie. let the user (developer) specify both the subtitles URL and mime type and look up the best match in supported protocols. The metadata options could look like this :

```javascript
{
  title: 'Some Movie Title',
  creator: 'John Doe',
  type: 'video', // can be 'video', 'audio' or 'image'
  subtitles: {
    url: 'http://url.to.some/subtitles.srt',
    contentType: 'text/srt'
  }
}
```

What do you think ?

**Comment by thibauts** [comment]
@jaruba AFAIK there is no really clean implementation of SSDP around. I planned to publish one as I already have some code (that needs some heaving testing though), but not seeing much interest and seriously lacking free time I put it aside some months ago. How do you feel the available implementation lacking ? I'd love to have your point of view on what pieces are missing.

**Comment by jaruba** [comment]
@thibauts From my current experience using [node-ssdp](https://github.com/diversario/node-ssdp), it fails to find the device many times.

Through testing I realized that the device is simply not found but available to connect to, so as @linuxenko mentioned about [nodecast-js](https://github.com/gyzerok/nodecast-js), I also realized that the best way to find the device is by retrying all the previously connected devices, and in many cases this works. But in other rare times, nothing except a restart will make the device work again.

About hearing that `nodecast-js` is good for discovery, I know for a fact that it was used in Isoplex before it went down, I also know it's being used now in Popcorn Time CE and Butter. I think the code is being used in some regard in Stremio too now. @vankasteelj posted some [demo code](https://github.com/jaruba/PowderPlayer/issues/51#issuecomment-158266350) for it, @Ivshti also took the time to strip the ssdp discovery from it and released it as [ssdp-js](https://www.npmjs.com/package/ssdp-js)

I know that @schizoduckie and @acidhax have started an epic project that tries to implement dlna *by the book*. but their also pretty busy these days (jan / feb have always been hell for devs), I'm not sure if their including discovery too in their plans though.

About forcing `mp4`, I've seen this done before: https://github.com/butterproject/butter-desktop/blob/master/src/app/lib/device/dlna.js#L52

Butter was forked from Popcorn Time after their lawsuits started, I know this was in their code before too, and it's been said it had the widest compatibility for DLNA. I also remember a previous chat with someone that said Samsung sometimes doesn't accept mkv even if it supports it, but forcing `mp4` makes it work from the first try.

I think that the hardest part for successful casting is that it also needs to take into account the wide range of bugs on the devices themselves..

**Comment by linuxenko** [comment]
> Regarding protocolInfo, where did you get this 'http-get:*:video/mp4:DLNA.ORG_PN=AVC_MP4_BL_CIF15_AAC_520;' ? Having this hard-coded probably won't play well with video formats other than MP4. One way to handle this specific

You are looking at README.md  ))) There is code that make possible make custom ProtocolInfo part. Without this lg tvs does not work, via protocolinfo can be retreived preview images ad cover art (it displaying at the accepting receiving time), subtites and so on .

**Comment by linuxenko** [comment]
> About forcing mp4, I've seen this done before: https://github.com/butterproject/butter-desktop/blob/master/src/app/lib/device/dlna.js#L52

Aha, looks like nice DIDL-Light implementation.

But why do you all hardcode this ? I like node-upnp-mediarenderer-client because there i can pass custom metadata as a string or use builtin builder (with small improvement for protocolinfo i posted)

**Comment by thibauts** [comment]
@jaruba We're starting to mix many issues here. It would be better to open other issues if needed, or even use already existing issues. I'll try to answer anyway.

First this implementation and the underlying `upnp-device-client` actually have been made to follow the specs to the letter. And as far as I know they do.

Regarding mime type I'll say what I always said to people posting compatibility issues. You can't throw any fixed content type to your TV and expect it to guess the correct one. Some TVs ignore it completely and auto-detect, some do not. The README example only is an example. Parts of the specs deal with listing available content-types and providing a correct one during load. This isn't a SHOULD, apps really *have to* do it. If some TVs can deal with incorrect content-type good for them but you can't rely on it as a feature as this isn't in the standard (it pretty much goes *against* the standard, actually). I'm positive the specs are sometimes vague and above all that TV manufacturers sometimes don't follow them very closely, but the mime-type thing is pretty well defined and shouldn't be a road-block. As far as I can tell all issues I had about compatibility have been either 1) developers not providing the correct mime type or 2) developers failing to detect that the stream is not playable *at all* by their TV. If your requested mime type is not in the supported protocols list, you're out of luck. This isn't a problem on our side : the TV plainly doesn't support it. This probably should be detected in end-user software and given as feedback to the final user. This would avoid bug issues that can't be solved without them buying another TV. 

As a maintainer I'm tired to see this issue surface all the time as the solution has already been provided and it looks like nobody cared to even implement it. I guess it's simpler to post an issue and hope somebody will do some magic. But it doesn't help us much as a community. My role here is to refuse any compatibility fix without sample code demonstrating that correct handling of mime type doesn't solve the issue.

As for SSDP, the implementation you link to floods the local network with requests so it probably works better than discovering only one time on start but I'm not sure it's the way to go. The SSDP spec has provision for timeouts and it should be possible to implement a lib that first discovers to populate a list and then keeps it fresh by monitoring announces and obeying timeouts. Actually I think about coding it for some time but unfortunately I have very little time to allocate to playing with this.

**Comment by thibauts** [comment]
@linuxenko Sure I know it's from README.md. The rest of my comment still holds and I'd love to have your input.

**Comment by Ivshti** [comment]
@thibauts sorry for the off-topic, but can you provide some immediate suggestions for improving ssdp-js? I ripped the code out of nodecast and noticed it's sending a lot of requests, but I have no knowledge of the spec nor time to read it.

**Comment by thibauts** [comment]
@Ivshti I haven't good suggestions to provide as I only skimmed the surface of the code and stopped when I saw requests were fired every 5 seconds. I understand your lack of time but I think there's no shortcut here unfortunately. The spec is pretty short BTW. It's not very complicated.

**Pull request closed without merging**
